Completed Skeleton Structure
interest-protocol/sui-money-market-sdk pull request #1
Opened 2023-06-21 13:56 UTC by blockchainlover2019

## Contents
- Copy structure from `amm-sdk`
- Add `argTypes` to `sdk.types.ts`
- Add `deposit` function in `sdk/index.ts`

2023-06-21 17:36 UTC, josemvcerqueira requested changes

2023-06-21 17:36 UTC, josemvcerqueira commented on package.json
> +    "typescript": "^5.1.3"
I believe we are missing a couple of dev dependencies to correctly use TS paths, sort imports, etc...

https://github.com/interest-protocol/sui-amm-sdk/blob/main/package.json

line 48

2023-06-21 17:36 UTC, josemvcerqueira commented on src/constants/index.ts
> +    MM_MONEY_MARKET_STORAGE:
I assume MM stands for MONEY_MARKET? If so we can simply name it: MM_STORAGE. However, I personally prefer to always spell out the entire word and avoid acronyms.

2023-06-21 17:36 UTC, josemvcerqueira commented on src/sdk/sdk.types.ts
> +import { MakeMoveVecTransaction, TransactionBlock } from '@mysten/sui.js';
These look great!

2023-06-21 17:38 UTC, josemvcerqueira commented on src/sdk/index.ts
> +  }: DepositArgs): PromisedTransactionBlock {
- I believe this function does not need to be asynchronous
- I updated the module name from interface to ipx_money_market_sdk_interface (sorry about that xD). You can find the link here https://github.com/interest-protocol/money-market/blob/main/money-market/sources/sdk-interface.move

The rest looks great!

2023-06-21 20:55 UTC, blockchainlover2019 commented on package.json
> +    "typescript": "^5.1.3"
Okay, let me add them.

2023-06-21 20:56 UTC, blockchainlover2019 commented on src/constants/index.ts
> +    MM_MONEY_MARKET_STORAGE:
Okay, will do change.

2023-06-23 16:31 UTC, josemvcerqueira commented on src/sdk/index.ts
> +      target: `${objects.MONEY_MARKET_PACKAGE_ID}::interface::deposit`,
I believe it would be  target: `${objects.MONEY_MARKET_PACKAGE_ID}::ipx_money_market_sdk_interface::deposit`

2023-06-23 16:31 UTC, josemvcerqueira commented on src/sdk/index.ts
> +      target: `${objects.MONEY_MARKET_PACKAGE_ID}::interface::deposit`,
this is the file you would be calling: https://github.com/interest-protocol/money-market/blob/main/money-market/sources/sdk-interface.move

2023-06-23 16:33 UTC, blockchainlover2019 commented on src/sdk/index.ts
> +      target: `${objects.MONEY_MARKET_PACKAGE_ID}::interface::deposit`,
> I believe it would be target: `${objects.MONEY_MARKET_PACKAGE_ID}::ipx_money_market_sdk_interface::deposit`

gotcha. let me fix it

2023-06-23 16:36 UTC, merged